### ISSUE TITLE
Something happened and it broke again

### ISSUE THREAD

**Issue by Its2loud1** [asishrs/smartthings-ringalarmv2#40]
I didn’t change anything. 

![A97F2193-572D-4B36-ADD5-96F88FC04988](https://user-images.githubusercontent.com/49612825/77991223-1a6bdb80-72d8-11ea-8606-587c0659650e.jpeg)

**Comment by schpeen** [comment]
same here and I didn't change a thing.

**Comment by burn56** [comment]
Tried removing and reauthorizing.
But it just consistently generates 2fa codes.
I’m now locked out for 24 hours.

**Comment by jsabia85** [comment]
Same here, this is the 2 or 3 time it’s happened since I have set v3 up. Not sure what’s going on.

**Comment by asishrs** [comment]
It seems ring is clearing the auth token after a specific time; mine is broken as well. I started working for a fix for this but couldn't get time to finish due to the new work arrangement.

**Comment by Its2loud1** [comment]
Not unlike Ring to change things up.  These are stressful times. Totally understand. Wish there was some way I could help. Thanks for taking a look at it.

**Comment by ampersandru** [comment]
broke for me a couple days ago also. Tried to troubleshoot by:
1) just removing device and readding
2) removing and readding smartapp
3) removing AWS stack and readded

Nothing seems to work unfortunately :(

**Comment by Its2loud1** [comment]
This could explain why things are broken

https://blog.ring.com/2020/03/30/new-modes-feature-makes-it-easy-to-control-your-ring-devices-with-just-one-tap-on-the-app/?utm_source=Braze&utm_medium=Email&utm_campaign=CRM1328_Alarm_Modes_Active_Y_US_Q120&utm_content=Variant_1&utm_campaignid=a15f3ea737691bce7d78a560f511af3e

**Comment by asishrs** [comment]
I learned that Ring is using `one-time token` now instead of `long-lived token`. Today, I tested the API calls using the one-time tokens; the APIs are working as expected 🎉 This requires changes in Lambda and ST app (Ring Alarm Manager). I am planning to make this change over weekend. 🤞

**Comment by rickscherer** [comment]
Following so I'm alerted when resolved.

**Comment by asishrs** [comment]
I pushed the fix for this. Follow the deployment process described here https://github.com/asishrs/smartthings/blob/master/RELEASE.md#release-v-330

**Comment by GizmoGoody** [comment]
@asishrs I followed your instructions (including unpausing the API at the end), but the API call seems to be failing due to a token issue. I went into Ring Account and tapped on Ring Account Status, but nothing happens.
![Capture](https://user-images.githubusercontent.com/46235745/78521159-d8caad00-777d-11ea-8be2-050200b9b991.JPG)

**Comment by asishrs** [comment]
@GoodyGizmos After updating the ST app in the IDE, can you delete the ST app and reinstall that?

**Comment by Its2loud1** [comment]
Same for me Asish. Deleted and reinstalled the smart app. Now it won’t even log into Ring to receive 2FA

**Comment by burn56** [comment]
Followed the instructions, 2fa still not saving.
Let me know if you need logs of any sort.

**Comment by asishrs** [comment]
I uninstalled the ST App and reinstalled that and configure it. I saw an issue with ST app not starting the initialization process, I didn't see logs for a while. I opened the ST app and tap on Save once again then everything started working as normal.

**Comment by asishrs** [comment]
> Same for me Asish. Deleted and reinstalled the smart app. Now it won’t even log into Ring to receive 2FA

Did you click on `Enable 2FA` on Ring Account page.

**Comment by Its2loud1** [comment]
> > Same for me Asish. Deleted and reinstalled the smart app. Now it won’t even log into Ring to receive 2FA
> 
> Did you click on `Enable 2FA` on Ring Account page.

I had already set up 2FA.  Are you saying I need to do it again?

**Comment by burn56** [comment]
I take it back.
After I clicked status for 2fa, a few times, I got it to save.
So it’s working for me now.
Much thanks!

**Comment by asishrs** [comment]
> > > Same for me Asish. Deleted and reinstalled the smart app. Now it won’t even log into Ring to receive 2FA
> > 
> > 
> > Did you click on `Enable 2FA` on Ring Account page.
> 
> I had already set up 2FA. Are you saying I need to do it again?

I meant to ask, whether you tap the button `Have you enabled the Two factor Authentication (2FA)....` on `Ring Account` settings in ST app.

**Comment by Its2loud1** [comment]
Yes. Definitely.  Am I supposed to reset the token each time?  Cuz I’m not.

**Comment by asishrs** [comment]
> Yes. Definitely. Am I supposed to reset the token each time? Cuz I’m not.

No, that option only if you are seeing `Unauthorized` error in the logs.

**Comment by Its2loud1** [comment]
My logs

![1E0B5196-E8DF-4339-9238-09B7335EA3D4](https://user-images.githubusercontent.com/49612825/78527173-0b31d580-7791-11ea-8ef1-74222b7cd3ce.jpeg)

**Comment by asishrs** [comment]
> My logs
> 
> 
> 
> ![1E0B5196-E8DF-4339-9238-09B7335EA3D4](https://user-images.githubusercontent.com/49612825/78527173-0b31d580-7791-11ea-8ef1-74222b7cd3ce.jpeg)
> 
> 
> 
> 
Looks like an issue with initial login. May be wrong password.

Can you login to ring website using a computer and confirm your account login details?

**Comment by Its2loud1** [comment]
I’ve been locked out.  The 2FA codes were not saving in the smart app and ever time I would choose Ring Account Status it would resend the code. Now I cant do anything for 24 hours. 
![E81E69CB-4FB0-4FB2-BF26-395F504A23DD](https://user-images.githubusercontent.com/49612825/78528024-40d7be00-7793-11ea-9f57-3fa258f4113d.jpeg)

**Comment by asishrs** [comment]
> @asishrs I followed your instructions (including unpausing the API at the end), but the API call seems to be failing due to a token issue. I went into Ring Account and tapped on Ring Account Status, but nothing happens.
> 
> ![Capture](https://user-images.githubusercontent.com/46235745/78521159-d8caad00-777d-11ea-8be2-050200b9b991.JPG)

Can you to reinstall the ST app?

**Comment by Its2loud1** [comment]
What happens if you click “yes” for reset tokens? Then what?

**Comment by jsabia85** [comment]
I was able to get it to work, I had to delete the device and smart app and re-configure it.

I have noticed (even prior to this upgrade) Automation routines work maybe 75% of the time. I have routines to automatically arm and disable the Ring alarm and sometimes they do not work. Has anybody else seen this?

Here is a screenshot of my log, I was just able to reproduce it:

![image](https://user-images.githubusercontent.com/32626729/78575916-fb9aa700-77f9-11ea-88bb-eaa24c915c91.png)

**Comment by asishrs** [comment]
> What happens if you click “yes” for reset tokens? Then what?

That will reset the current tokens, you then need to switch it back to No and reconfigure your ring account login details in the ST app. The option is to avoid keep reinstall app due to token issues.

**Comment by asishrs** [comment]
> I was able to get it to work, I had to delete the device and smart app and re-configure it.
> 
> 
> 
> I have noticed (even prior to this upgrade) Automation routines work maybe 75% of the time. I have routines to automatically arm and disable the Ring alarm and sometimes they do not work. Has anybody else seen this?
> 
> 
> 
> Here is a screenshot of my log, I was just able to reproduce it:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/32626729/78575916-fb9aa700-77f9-11ea-88bb-eaa24c915c91.png)
> 
> 

I can think of few reasons for this.
-  Lambda taking more than 10 seconds to respond to the `status` api call. ST timeout all synchronous api calls in 10 seconds.
- Total execution time of the function in ST app taking more than 40 seconds. ST timeout any scheduled calls taking more than 40 seconds.

**Comment by GizmoGoody** [comment]
> @GoodyGizmos After updating the ST app in the IDE, can you delete the ST app and reinstall that?

@asishrs I deleted the SmartApp and re-installed/re-setup with 2FA and it reconnected no problems including my WebCore integration. I'll let you know if I notice anything else.

Also, it looks like you've removed the child device status from the Ring Alarm device. Was that intentional since that information is available under each of the child devices?

**Comment by asishrs** [comment]
> > @GoodyGizmos After updating the ST app in the IDE, can you delete the ST app and reinstall that?
> 
> 
> 
> @asishrs I deleted the SmartApp and re-installed/re-setup with 2FA and it reconnected no problems including my WebCore integration. I'll let you know if I notice anything else.
> 
> 
> 
> Also, it looks like you've removed the child device status from the Ring Alarm device. Was that intentional since that information is available under each of the child devices?

The ring api that I used for that is no more available 😔

**Comment by schpeen** [comment]
I am getting that stupid problem again where I cant click on ring status it just keeps sending me another code and never gives me the status. I followed the new instructions perfectly. Why I hate 2fa.....I am plenty happy with just using a complex password. I am afraid to keep trying or I am going to get locked out.

**Comment by Its2loud1** [comment]
> I am getting that stupid problem again where I cant click on ring status it just keeps sending me another code and never gives me the status. I followed the new instructions perfectly. Why I hate 2fa.....I am plenty happy with just using a complex password. I am afraid to keep trying or I am going to get locked out.

This is the exact same thing that happened to me and then Ring locked me out for 24hrs.

**Comment by burn56** [comment]
@schpeen @Its2loud1 
I had the same issue.
I used the reset feature flipped it to yes.  Waited.  Then flipped it to no.

Then when I got the 2fa, entered the code.
Then hit status, and it gave me another code.  Only this time instead of using the iphones auto full feature, I expanded the text by pulling down the message.
Then dismissed the notification.

Once I did, suddenly status page loaded.
Not saying this is the fix, but this is what worked for me.

**Comment by jsabia85** [comment]
> > I was able to get it to work, I had to delete the device and smart app and re-configure it.
> > I have noticed (even prior to this upgrade) Automation routines work maybe 75% of the time. I have routines to automatically arm and disable the Ring alarm and sometimes they do not work. Has anybody else seen this?
> > Here is a screenshot of my log, I was just able to reproduce it:
> > ![image](https://user-images.githubusercontent.com/32626729/78575916-fb9aa700-77f9-11ea-88bb-eaa24c915c91.png)
> 
> I can think of few reasons for this.
> 
> * Lambda taking more than 10 seconds to respond to the `status` api call. ST timeout all synchronous api calls in 10 seconds.
> * Total execution time of the function in ST app taking more than 40 seconds. ST timeout any scheduled calls taking more than 40 seconds.

Is it possible to leverage WebCoRE to actually arm stay/away and disarm with this integration? I don’t see a way to do it as I don’t have the options in WebCoRE for arm/disarm.

**Comment by ampersandru** [comment]
> > > I was able to get it to work, I had to delete the device and smart app and re-configure it.
> > > I have noticed (even prior to this upgrade) Automation routines work maybe 75% of the time. I have routines to automatically arm and disable the Ring alarm and sometimes they do not work. Has anybody else seen this?
> > > Here is a screenshot of my log, I was just able to reproduce it:
> > > ![image](https://user-images.githubusercontent.com/32626729/78575916-fb9aa700-77f9-11ea-88bb-eaa24c915c91.png)
> > 
> > 
> > I can think of few reasons for this.
> > 
> > * Lambda taking more than 10 seconds to respond to the `status` api call. ST timeout all synchronous api calls in 10 seconds.
> > * Total execution time of the function in ST app taking more than 40 seconds. ST timeout any scheduled calls taking more than 40 seconds.
> 
> Is it possible to leverage WebCoRE to actually arm stay/away and disarm with this integration? I don’t see a way to do it as I don’t have the options in WebCoRE for arm/disarm.

Did you share the ring alarm system to webcore? You can arm/disarm with webcore. I added the following as a backup incase the regular automations didnt work correctly

![image](https://user-images.githubusercontent.com/43594741/78610764-6a87f800-781a-11ea-92ab-bcad021ba7f1.png)

**Comment by jsabia85** [comment]
> > > > I was able to get it to work, I had to delete the device and smart app and re-configure it.
> > > > I have noticed (even prior to this upgrade) Automation routines work maybe 75% of the time. I have routines to automatically arm and disable the Ring alarm and sometimes they do not work. Has anybody else seen this?
> > > > Here is a screenshot of my log, I was just able to reproduce it:
> > > > ![image](https://user-images.githubusercontent.com/32626729/78575916-fb9aa700-77f9-11ea-88bb-eaa24c915c91.png)
> > > 
> > > 
> > > I can think of few reasons for this.
> > > 
> > > * Lambda taking more than 10 seconds to respond to the `status` api call. ST timeout all synchronous api calls in 10 seconds.
> > > * Total execution time of the function in ST app taking more than 40 seconds. ST timeout any scheduled calls taking more than 40 seconds.
> > 
> > 
> > Is it possible to leverage WebCoRE to actually arm stay/away and disarm with this integration? I don’t see a way to do it as I don’t have the options in WebCoRE for arm/disarm.
> 
> Did you share the ring alarm system to webcore? You can arm/disarm with webcore. I added the following as a backup incase the regular automations didnt work correctly
> 
> ![image](https://user-images.githubusercontent.com/43594741/78610764-6a87f800-781a-11ea-92ab-bcad021ba7f1.png)

Thank you for this!

**Comment by SupaTWC** [comment]
My ring alarm would get stuck at pending off and won't disarm. How do I force an update to get it to send the off command again?

**Comment by asishrs** [comment]
Are you using the latest version of app?

**Comment by SupaTWC** [comment]
Yeah, updated today.

**Comment by SupaTWC** [comment]
I have no problem arming it, disarm works about 40% of the time.

**Comment by jaas666** [comment]
Mine stopped working also.. deleted everything updated lambda function/ updated device handler / updated smart app

I get the 2FA code and enter it but the status shows the Location and Ring ZID empty.. refresh token and access token do contain data.

The device shows as online on Smart Things but can't arm/disarm.. It changes status on the SmartThings app but not on the actual alarm.

**Comment by ricklacy** [comment]
Not sure if I'm just doing it wrong or what, but I've tried several times following the instructions, and get the attached error. Also, it's not prompting for 2FA
![log](https://user-images.githubusercontent.com/27033977/79021890-5c034e80-7b42-11ea-8eb4-4e65b714c4e0.JPG)

**Comment by asishrs** [comment]
> I have no problem arming it, disarm works about 40% of the time.

I have a new build with extra logging https://github.com/asishrs/smartthings/blob/master/RELEASE.md#release-v340 

Once you update to this version get me below to troubleshoot this issue.
- Get all device logs by tapping Ring Alarm Manager > Advanced Settings > Debug Logs. After you do this, you can check the logs on AWS Cloud Watch.
- Ring Alarm Manager logs from ST IDE for the devices call.
- Ring Alarm Manager logs from ST IDE for the failed status call.
- Ring Alarm Device handler logs from ST IDE for the failed status call.

**Comment by asishrs** [comment]
> Not sure if I'm just doing it wrong or what, but I've tried several times following the instructions, and get the attached error. Also, it's not prompting for 2FA
> ![log](https://user-images.githubusercontent.com/27033977/79021890-5c034e80-7b42-11ea-8eb4-4e65b714c4e0.JPG)

Are you using the latest version of Lambda and ST app. https://github.com/asishrs/smartthings/blob/master/RELEASE.md#release-v340

**Comment by ricklacy** [comment]
Actually I have 3.3.0, the one posted last week. I'll give this one a try
